### ISSUE TITLE
sppasTime class doesn't work for negative GMT offsets

### ISSUE THREAD

**Issue by sbrodeur** [brigittebigi/sppas#13]
I get the following error trying to launch SPPAS 1.9.7:
```
Traceback (most recent call last):
  File "sppas/sppas/bin/sppasgui.py", line 69, in <module>
    from sppas.src.ui.wxgui.frames.mainframe import FrameSPPAS
  File "sppas/sppas/src/ui/wxgui/frames/mainframe.py", line 78, in <module>
    from sppas.src.ui.wxgui.frames.sppaseditframe import SppasEditFrame
  File "sppas/sppas/src/ui/wxgui/frames/sppaseditframe.py", line 50, in <module>
    from sppas.src.ui.wxgui.demo.wizardDisplayDemo import WizardDisplayDemo
  File "sppas/sppas/src/ui/wxgui/demo/wizardDisplayDemo.py", line 48, in <module>
    from .TierCtrlDemo import TierCtrlDemo
  File "sppas/sppas/src/ui/wxgui/demo/TierCtrlDemo.py", line 49, in <module>
    trs = sppas.src.annotationdata.aio.read( os.path.join(os.path.dirname(os.path.abspath(__file__)),"oriana1-merge.TextGrid"))
  File "sppas/sppas/src/annotationdata/aio/__init__.py", line 177, in read
    trs = parser.read()
  File "sppas/sppas/src/anndata/aio/readwrite.py", line 167, in read
    trs.set_meta('file_read_date', sppasTime().now)
  File "sppas/sppas/src/utils/datatype.py", line 86, in __init__
    raise UtilsDataTypeError("sppasTime(now)", "%Y-%m-%dT%H:%M:%S{:0=+3d}:{:0=2d}", now)
sppas.src.utils.utilsexc.UtilsDataTypeError: ':ERROR 7010: Expected a sppasTime(now) of type %Y-%m-%dT%H:%M:%S{:0=+3d}:{:0=2d}. Got None instead.'
```

Looking at the code in _sppas/sppas/src/utils/datatype.py_ , it seems that a positive GMT is expected during formatting. The thing is I am in Canada and we have GMT-4 right now:
```
2018-08-14T09:28:02-04:00
```

**Comment by brigittebigi** [comment]
Many thanks for signaling the bug, it will be corrected in the next version (expect it mid- or end- September).
