### ISSUE TITLE
Error u"filename" when apply plugin

### ISSUE THREAD

**Issue by brigittebigi** [brigittebigi/sppas#9]
Traceback (most recent call last):
  File "/Users/adminlocal/PycharmProjects/sppas/sppas/src/wxgui/panels/pplugins.py", line 235, in OnApply
    log_text = self._manager.run_plugin(plugin_id, file_names)
  File "/Users/adminlocal/PycharmProjects/sppas/sppas/src/plugins/manager.py", line 237, in run_plugin
    output_lines += get_info("4010").format(pfile)
KeyError: u'filename'

**Comment by brigittebigi** [comment]
verified under branch develop.
the branch master is OK (sppas-1.8.3).

**Comment by brigittebigi** [comment]
corrected.
